FROM nginx
# We are overriding the default default.conf file, if exists
# [so not specifying the file name will do nothing if it exists?]
# [the command in the docs is COPY nginx.conf /etc/nginx/nginx.conf, so what's conf.d??]
COPY ./default.conf /etc/nginx/conf.d/default.conf